//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 07/10/2022 08:46:16
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.ComponentModel;
using System.Reflection;
using System.Data.Common;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Internal;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Infrastructure;
using appglobal;

namespace jasuindo_models
{

    public partial class model_user_managemen : DbContext
    {

        public model_user_managemen() :
            base()
        {
            OnCreated();
        }

        public model_user_managemen(DbContextOptions<model_user_managemen> options) :
            base(options)
        {
            OnCreated();
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured ||
                (!optionsBuilder.Options.Extensions.OfType<RelationalOptionsExtension>().Any(ext => !string.IsNullOrEmpty(ext.ConnectionString) || ext.Connection != null) &&
                 !optionsBuilder.Options.Extensions.Any(ext => !(ext is RelationalOptionsExtension) && !(ext is CoreOptionsExtension))))
            {
                optionsBuilder.UseNpgsql(AppGlobal.get_connection_string());
            }
            CustomizeConfiguration(ref optionsBuilder);
            base.OnConfiguring(optionsBuilder);
        }

        partial void CustomizeConfiguration(ref DbContextOptionsBuilder optionsBuilder);

        public virtual DbSet<m_organisasi> m_organisasi
        {
            get;
            set;
        }

        public virtual DbSet<m_lokasi> m_lokasi
        {
            get;
            set;
        }

        public virtual DbSet<m_kelurahan_desa> m_kelurahan_desa
        {
            get;
            set;
        }

        public virtual DbSet<m_feature> m_feature
        {
            get;
            set;
        }

        public virtual DbSet<map_feature_group> map_feature_group
        {
            get;
            set;
        }

        public virtual DbSet<m_group_user> m_group_user
        {
            get;
            set;
        }

        public virtual DbSet<m_user> m_user
        {
            get;
            set;
        }

        public virtual DbSet<map_group_user> map_group_user
        {
            get;
            set;
        }

        public virtual DbSet<m_action_feature> m_action_feature
        {
            get;
            set;
        }

        public virtual DbSet<m_project_application> m_project_application
        {
            get;
            set;
        }

        public virtual DbSet<map_user_lokasi> map_user_lokasi
        {
            get;
            set;
        }

        public virtual DbSet<m_group_feature> m_group_feature
        {
            get;
            set;
        }

        public virtual DbSet<map_feature_group_project> map_feature_group_project
        {
            get;
            set;
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            this.m_organisasiMapping(modelBuilder);
            this.Customizem_organisasiMapping(modelBuilder);

            this.m_lokasiMapping(modelBuilder);
            this.Customizem_lokasiMapping(modelBuilder);

            this.m_kelurahan_desaMapping(modelBuilder);
            this.Customizem_kelurahan_desaMapping(modelBuilder);

            this.m_featureMapping(modelBuilder);
            this.Customizem_featureMapping(modelBuilder);

            this.map_feature_groupMapping(modelBuilder);
            this.Customizemap_feature_groupMapping(modelBuilder);

            this.m_group_userMapping(modelBuilder);
            this.Customizem_group_userMapping(modelBuilder);

            this.m_userMapping(modelBuilder);
            this.Customizem_userMapping(modelBuilder);

            this.map_group_userMapping(modelBuilder);
            this.Customizemap_group_userMapping(modelBuilder);

            this.m_action_featureMapping(modelBuilder);
            this.Customizem_action_featureMapping(modelBuilder);

            this.m_project_applicationMapping(modelBuilder);
            this.Customizem_project_applicationMapping(modelBuilder);

            this.map_user_lokasiMapping(modelBuilder);
            this.Customizemap_user_lokasiMapping(modelBuilder);

            this.m_group_featureMapping(modelBuilder);
            this.Customizem_group_featureMapping(modelBuilder);

            this.map_feature_group_projectMapping(modelBuilder);
            this.Customizemap_feature_group_projectMapping(modelBuilder);

            RelationshipsMapping(modelBuilder);
            CustomizeMapping(ref modelBuilder);
        }

        #region m_organisasi Mapping

        private void m_organisasiMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<m_organisasi>().ToTable(@"m_organisasi");
            modelBuilder.Entity<m_organisasi>().Property<int>(x => x.m_organisasi_id).HasColumnName(@"m_organisasi_id").IsRequired().ValueGeneratedOnAdd();
            modelBuilder.Entity<m_organisasi>().Property<string>(x => x.nama_oganisasi).HasColumnName(@"nama_oganisasi").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<m_organisasi>().Property<string>(x => x.alamat_organisasi).HasColumnName(@"alamat_organisasi").ValueGeneratedNever();
            modelBuilder.Entity<m_organisasi>().Property<bool>(x => x.status_aktif).HasColumnName(@"status_aktif").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<m_organisasi>().Property<string>(x => x.email_organisasi).HasColumnName(@"email_organisasi").ValueGeneratedNever();
            modelBuilder.Entity<m_organisasi>().Property<string>(x => x.website_organisasi).HasColumnName(@"website_organisasi").ValueGeneratedNever();
            modelBuilder.Entity<m_organisasi>().Property<string>(x => x.telepon_organisasi).HasColumnName(@"telepon_organisasi").ValueGeneratedNever();
            modelBuilder.Entity<m_organisasi>().Property<string>(x => x.path_logo_organiasi).HasColumnName(@"path_logo_organiasi").ValueGeneratedNever();
            modelBuilder.Entity<m_organisasi>().Property<string>(x => x.npwp_organiasi).HasColumnName(@"npwp_organiasi").ValueGeneratedNever();
            modelBuilder.Entity<m_organisasi>().Property<System.DateTime?>(x => x.create_at).HasColumnName(@"create_at").ValueGeneratedNever();
            modelBuilder.Entity<m_organisasi>().Property<string>(x => x.create_by).HasColumnName(@"create_by").ValueGeneratedNever();
            modelBuilder.Entity<m_organisasi>().Property<System.DateTime?>(x => x.update_at).HasColumnName(@"update_at").ValueGeneratedNever();
            modelBuilder.Entity<m_organisasi>().Property<string>(x => x.update_by).HasColumnName(@"update_by").ValueGeneratedNever();
            modelBuilder.Entity<m_organisasi>().HasKey(@"m_organisasi_id");
        }

        partial void Customizem_organisasiMapping(ModelBuilder modelBuilder);

        #endregion

        #region m_lokasi Mapping

        private void m_lokasiMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<m_lokasi>().ToTable(@"m_lokasi");
            modelBuilder.Entity<m_lokasi>().Property<int>(x => x.m_lokasi_id).HasColumnName(@"m_lokasi_id").IsRequired().ValueGeneratedOnAdd();
            modelBuilder.Entity<m_lokasi>().Property<int>(x => x.m_organisasi_id).HasColumnName(@"m_organisasi_id").ValueGeneratedNever();
            modelBuilder.Entity<m_lokasi>().Property<int>(x => x.parent_lokasi_id).HasColumnName(@"parent_lokasi_id").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<m_lokasi>().Property<int>(x => x.parent_index).HasColumnName(@"parent_index").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<m_lokasi>().Property<string>(x => x.nama_lokasi).HasColumnName(@"nama_lokasi").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<m_lokasi>().Property<string>(x => x.kode_lokasi).HasColumnName(@"kode_lokasi").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<m_lokasi>().Property<string>(x => x.provinsi).HasColumnName(@"provinsi").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<m_lokasi>().Property<string>(x => x.kabupaten).HasColumnName(@"kabupaten").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<m_lokasi>().Property<string>(x => x.kecamatan).HasColumnName(@"kecamatan").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<m_lokasi>().Property<string>(x => x.kelurahan).HasColumnName(@"kelurahan").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<m_lokasi>().Property<string>(x => x.alamat).HasColumnName(@"alamat").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<m_lokasi>().Property<bool>(x => x.status_aktif).HasColumnName(@"status_aktif").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<m_lokasi>().Property<System.DateTime?>(x => x.create_at).HasColumnName(@"create_at").ValueGeneratedNever();
            modelBuilder.Entity<m_lokasi>().Property<string>(x => x.create_by).HasColumnName(@"create_by").ValueGeneratedNever();
            modelBuilder.Entity<m_lokasi>().Property<System.DateTime?>(x => x.update_at).HasColumnName(@"update_at").ValueGeneratedNever();
            modelBuilder.Entity<m_lokasi>().Property<string>(x => x.update_by).HasColumnName(@"update_by").ValueGeneratedNever();
            modelBuilder.Entity<m_lokasi>().Property<string>(x => x.name_location_secondary).HasColumnName(@"name_location_secondary").ValueGeneratedNever();
            modelBuilder.Entity<m_lokasi>().HasKey(@"m_lokasi_id");
        }

        partial void Customizem_lokasiMapping(ModelBuilder modelBuilder);

        #endregion

        #region m_kelurahan_desa Mapping

        private void m_kelurahan_desaMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<m_kelurahan_desa>().ToTable(@"m_kelurahan_desa");
            modelBuilder.Entity<m_kelurahan_desa>().Property<string>(x => x.m_kelurahan_desa_id).HasColumnName(@"m_kelurahan_desa_id").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<m_kelurahan_desa>().Property<string>(x => x.nama_kelurahan_desa).HasColumnName(@"nama_kelurahan_desa").IsRequired().ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<m_kelurahan_desa>().Property<string>(x => x.nama_kecamatan).HasColumnName(@"nama_kecamatan").IsRequired().ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<m_kelurahan_desa>().Property<string>(x => x.nama_kabupaten_kota).HasColumnName(@"nama_kabupaten_kota").IsRequired().ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<m_kelurahan_desa>().Property<string>(x => x.jenis_kabupaten_kota).HasColumnName(@"jenis_kabupaten_kota").IsRequired().ValueGeneratedNever().HasMaxLength(10);
            modelBuilder.Entity<m_kelurahan_desa>().Property<string>(x => x.nama_propinsi).HasColumnName(@"nama_propinsi").IsRequired().ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<m_kelurahan_desa>().Property<string>(x => x.kode_pos).HasColumnName(@"kode_pos").IsRequired().ValueGeneratedNever().HasMaxLength(10);
            modelBuilder.Entity<m_kelurahan_desa>().HasKey(@"m_kelurahan_desa_id");
        }

        partial void Customizem_kelurahan_desaMapping(ModelBuilder modelBuilder);

        #endregion

        #region m_feature Mapping

        private void m_featureMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<m_feature>().ToTable(@"m_feature");
            modelBuilder.Entity<m_feature>().Property<int>(x => x.m_feature_id).HasColumnName(@"m_feature_id").IsRequired().ValueGeneratedOnAdd();
            modelBuilder.Entity<m_feature>().Property<string>(x => x.m_feature_name).HasColumnName(@"m_feature_name").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<m_feature>().Property<int?>(x => x.index).HasColumnName(@"index").ValueGeneratedNever();
            modelBuilder.Entity<m_feature>().Property<string>(x => x.name_link_feature).HasColumnName(@"name_link_feature").ValueGeneratedNever();
            modelBuilder.Entity<m_feature>().Property<bool>(x => x.status).HasColumnName(@"status").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<m_feature>().Property<System.DateTime?>(x => x.create_at).HasColumnName(@"create_at").ValueGeneratedNever();
            modelBuilder.Entity<m_feature>().Property<string>(x => x.create_by).HasColumnName(@"create_by").ValueGeneratedNever();
            modelBuilder.Entity<m_feature>().Property<System.DateTime?>(x => x.update_at).HasColumnName(@"update_at").ValueGeneratedNever();
            modelBuilder.Entity<m_feature>().Property<string>(x => x.update_by).HasColumnName(@"update_by").ValueGeneratedNever();
            modelBuilder.Entity<m_feature>().Property<string>(x => x.feature_icon).HasColumnName(@"feature_icon").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<m_feature>().HasKey(@"m_feature_id");
        }

        partial void Customizem_featureMapping(ModelBuilder modelBuilder);

        #endregion

        #region map_feature_group Mapping

        private void map_feature_groupMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<map_feature_group>().ToTable(@"map_feature_group");
            modelBuilder.Entity<map_feature_group>().Property<System.Guid>(x => x.map_feature_group_id).HasColumnName(@"map_feature_group_id").IsRequired().ValueGeneratedOnAdd();
            modelBuilder.Entity<map_feature_group>().Property<int>(x => x.m_group_user_id).HasColumnName(@"m_group_user_id").ValueGeneratedNever();
            modelBuilder.Entity<map_feature_group>().Property<string>(x => x.action_feature).HasColumnName(@"action_feature").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<map_feature_group>().Property<System.DateTime?>(x => x.create_at).HasColumnName(@"create_at").ValueGeneratedNever();
            modelBuilder.Entity<map_feature_group>().Property<string>(x => x.create_by).HasColumnName(@"create_by").ValueGeneratedNever();
            modelBuilder.Entity<map_feature_group>().Property<System.DateTime?>(x => x.update_at).HasColumnName(@"update_at").ValueGeneratedNever();
            modelBuilder.Entity<map_feature_group>().Property<string>(x => x.update_by).HasColumnName(@"update_by").ValueGeneratedNever();
            modelBuilder.Entity<map_feature_group>().Property<System.Guid>(x => x.map_feature_group_project_id).HasColumnName(@"map_feature_group_project_id").ValueGeneratedNever();
            modelBuilder.Entity<map_feature_group>().HasKey(@"map_feature_group_id");
        }

        partial void Customizemap_feature_groupMapping(ModelBuilder modelBuilder);

        #endregion

        #region m_group_user Mapping

        private void m_group_userMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<m_group_user>().ToTable(@"m_group_user");
            modelBuilder.Entity<m_group_user>().Property<int>(x => x.m_group_user_id).HasColumnName(@"m_group_user_id").IsRequired().ValueGeneratedOnAdd();
            modelBuilder.Entity<m_group_user>().Property<string>(x => x.m_group_user_name).HasColumnName(@"m_group_user_name").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<m_group_user>().Property<bool>(x => x.status).HasColumnName(@"status").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<m_group_user>().Property<System.DateTime?>(x => x.create_at).HasColumnName(@"create_at").ValueGeneratedNever();
            modelBuilder.Entity<m_group_user>().Property<string>(x => x.create_by).HasColumnName(@"create_by").ValueGeneratedNever();
            modelBuilder.Entity<m_group_user>().Property<System.DateTime?>(x => x.update_at).HasColumnName(@"update_at").ValueGeneratedNever();
            modelBuilder.Entity<m_group_user>().Property<string>(x => x.update_by).HasColumnName(@"update_by").ValueGeneratedNever();
            modelBuilder.Entity<m_group_user>().HasKey(@"m_group_user_id");
        }

        partial void Customizem_group_userMapping(ModelBuilder modelBuilder);

        #endregion

        #region m_user Mapping

        private void m_userMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<m_user>().ToTable(@"m_user");
            modelBuilder.Entity<m_user>().Property<System.Guid>(x => x.m_user_id).HasColumnName(@"m_user_id").IsRequired().ValueGeneratedOnAdd();
            modelBuilder.Entity<m_user>().Property<string>(x => x.m_username).HasColumnName(@"m_username").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<m_user>().Property<string>(x => x.m_user_password).HasColumnName(@"m_user_password").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<m_user>().Property<string>(x => x.m_user_email).HasColumnName(@"m_user_email").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<m_user>().Property<bool>(x => x.status).HasColumnName(@"status").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<m_user>().Property<string>(x => x.status_aktif).HasColumnName(@"status_aktif").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<m_user>().Property<System.DateTime?>(x => x.create_at).HasColumnName(@"create_at").ValueGeneratedNever();
            modelBuilder.Entity<m_user>().Property<string>(x => x.create_by).HasColumnName(@"create_by").ValueGeneratedNever();
            modelBuilder.Entity<m_user>().Property<System.DateTime?>(x => x.update_at).HasColumnName(@"update_at").ValueGeneratedNever();
            modelBuilder.Entity<m_user>().Property<string>(x => x.update_by).HasColumnName(@"update_by").ValueGeneratedNever();
            modelBuilder.Entity<m_user>().Property<string>(x => x.ref1).HasColumnName(@"ref1").ValueGeneratedNever();
            modelBuilder.Entity<m_user>().Property<string>(x => x.ref2).HasColumnName(@"ref2").ValueGeneratedNever();
            modelBuilder.Entity<m_user>().Property<string>(x => x.ref3).HasColumnName(@"ref3").ValueGeneratedNever();
            modelBuilder.Entity<m_user>().HasKey(@"m_user_id");
        }

        partial void Customizem_userMapping(ModelBuilder modelBuilder);

        #endregion

        #region map_group_user Mapping

        private void map_group_userMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<map_group_user>().ToTable(@"map_group_user");
            modelBuilder.Entity<map_group_user>().Property<System.Guid>(x => x.map_group_user_id).HasColumnName(@"map_group_user_id").IsRequired().ValueGeneratedOnAdd();
            modelBuilder.Entity<map_group_user>().Property<bool>(x => x.status_aktif).HasColumnName(@"status_aktif").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<map_group_user>().Property<int>(x => x.m_group_user_id).HasColumnName(@"m_group_user_id").ValueGeneratedNever();
            modelBuilder.Entity<map_group_user>().Property<int>(x => x.m_project_application_id).HasColumnName(@"m_project_application_id").ValueGeneratedNever();
            modelBuilder.Entity<map_group_user>().Property<System.Guid>(x => x.m_user_id).HasColumnName(@"m_user_id").ValueGeneratedNever();
            modelBuilder.Entity<map_group_user>().Property<System.DateTime?>(x => x.create_at).HasColumnName(@"create_at").ValueGeneratedNever();
            modelBuilder.Entity<map_group_user>().Property<string>(x => x.create_by).HasColumnName(@"create_by").ValueGeneratedNever();
            modelBuilder.Entity<map_group_user>().Property<System.DateTime?>(x => x.update_at).HasColumnName(@"update_at").ValueGeneratedNever();
            modelBuilder.Entity<map_group_user>().Property<string>(x => x.update_by).HasColumnName(@"update_by").ValueGeneratedNever();
            modelBuilder.Entity<map_group_user>().HasKey(@"map_group_user_id");
        }

        partial void Customizemap_group_userMapping(ModelBuilder modelBuilder);

        #endregion

        #region m_action_feature Mapping

        private void m_action_featureMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<m_action_feature>().ToTable(@"m_action_feature");
            modelBuilder.Entity<m_action_feature>().Property<int>(x => x.m_action_feature_id).HasColumnName(@"m_action_feature_id").IsRequired().ValueGeneratedOnAdd();
            modelBuilder.Entity<m_action_feature>().Property<string>(x => x.m_action_feature_name).HasColumnName(@"m_action_feature_name").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<m_action_feature>().Property<System.DateTime?>(x => x.create_at).HasColumnName(@"create_at").ValueGeneratedNever();
            modelBuilder.Entity<m_action_feature>().Property<string>(x => x.create_by).HasColumnName(@"create_by").ValueGeneratedNever();
            modelBuilder.Entity<m_action_feature>().Property<System.DateTime?>(x => x.update_at).HasColumnName(@"update_at").ValueGeneratedNever();
            modelBuilder.Entity<m_action_feature>().Property<string>(x => x.update_by).HasColumnName(@"update_by").ValueGeneratedNever();
            modelBuilder.Entity<m_action_feature>().Property<bool>(x => x.status).HasColumnName(@"status").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<m_action_feature>().HasKey(@"m_action_feature_id");
            modelBuilder.Entity<m_action_feature>().HasIndex(@"m_action_feature_name").IsUnique(true);
        }

        partial void Customizem_action_featureMapping(ModelBuilder modelBuilder);

        #endregion

        #region m_project_application Mapping

        private void m_project_applicationMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<m_project_application>().ToTable(@"m_project_application");
            modelBuilder.Entity<m_project_application>().Property<int>(x => x.m_project_application_id).HasColumnName(@"m_project_application_id").IsRequired().ValueGeneratedOnAdd();
            modelBuilder.Entity<m_project_application>().Property<string>(x => x.m_project_application_name).HasColumnName(@"m_project_application_name").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<m_project_application>().Property<bool>(x => x.status_aktif).HasColumnName(@"status_aktif").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<m_project_application>().Property<string>(x => x.key_project).HasColumnName(@"key_project").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<m_project_application>().Property<System.DateTime?>(x => x.create_at).HasColumnName(@"create_at").ValueGeneratedNever();
            modelBuilder.Entity<m_project_application>().Property<string>(x => x.create_by).HasColumnName(@"create_by").ValueGeneratedNever();
            modelBuilder.Entity<m_project_application>().Property<System.DateTime?>(x => x.update_at).HasColumnName(@"update_at").ValueGeneratedNever();
            modelBuilder.Entity<m_project_application>().Property<string>(x => x.update_by).HasColumnName(@"update_by").ValueGeneratedNever();
            modelBuilder.Entity<m_project_application>().Property<string>(x => x.type_project).HasColumnName(@"type_project").ValueGeneratedNever();
            modelBuilder.Entity<m_project_application>().Property<string>(x => x.scope_fitur_project).HasColumnName(@"scope_fitur_project").ValueGeneratedNever();
            modelBuilder.Entity<m_project_application>().HasKey(@"m_project_application_id");
        }

        partial void Customizem_project_applicationMapping(ModelBuilder modelBuilder);

        #endregion

        #region map_user_lokasi Mapping

        private void map_user_lokasiMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<map_user_lokasi>().ToTable(@"map_user_lokasi");
            modelBuilder.Entity<map_user_lokasi>().Property<System.Guid>(x => x.map_user_lokasi_id).HasColumnName(@"map_user_lokasi_id").IsRequired().ValueGeneratedOnAdd();
            modelBuilder.Entity<map_user_lokasi>().Property<System.DateTime?>(x => x.create_at).HasColumnName(@"create_at").ValueGeneratedNever();
            modelBuilder.Entity<map_user_lokasi>().Property<string>(x => x.create_by).HasColumnName(@"create_by").ValueGeneratedNever();
            modelBuilder.Entity<map_user_lokasi>().Property<System.DateTime?>(x => x.update_at).HasColumnName(@"update_at").ValueGeneratedNever();
            modelBuilder.Entity<map_user_lokasi>().Property<string>(x => x.update_by).HasColumnName(@"update_by").ValueGeneratedNever();
            modelBuilder.Entity<map_user_lokasi>().Property<System.Guid>(x => x.m_user_id).HasColumnName(@"m_user_id").ValueGeneratedNever();
            modelBuilder.Entity<map_user_lokasi>().Property<int>(x => x.m_project_application_id).HasColumnName(@"m_project_application_id").ValueGeneratedNever();
            modelBuilder.Entity<map_user_lokasi>().Property<int>(x => x.m_lokasi_id).HasColumnName(@"m_lokasi_id").ValueGeneratedNever();
            modelBuilder.Entity<map_user_lokasi>().HasKey(@"map_user_lokasi_id");
        }

        partial void Customizemap_user_lokasiMapping(ModelBuilder modelBuilder);

        #endregion

        #region m_group_feature Mapping

        private void m_group_featureMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<m_group_feature>().ToTable(@"m_group_feature");
            modelBuilder.Entity<m_group_feature>().Property<int>(x => x.m_group_feature_id).HasColumnName(@"m_group_feature_id").IsRequired().ValueGeneratedOnAdd();
            modelBuilder.Entity<m_group_feature>().Property<bool>(x => x.status).HasColumnName(@"status").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<m_group_feature>().Property<int>(x => x.index).HasColumnName(@"index").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<m_group_feature>().Property<System.DateTime?>(x => x.create_at).HasColumnName(@"create_at").ValueGeneratedNever();
            modelBuilder.Entity<m_group_feature>().Property<string>(x => x.create_by).HasColumnName(@"create_by").ValueGeneratedNever();
            modelBuilder.Entity<m_group_feature>().Property<System.DateTime?>(x => x.update_at).HasColumnName(@"update_at").ValueGeneratedNever();
            modelBuilder.Entity<m_group_feature>().Property<string>(x => x.update_by).HasColumnName(@"update_by").ValueGeneratedNever();
            modelBuilder.Entity<m_group_feature>().Property<string>(x => x.group_feature_name).HasColumnName(@"group_feature_name").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<m_group_feature>().HasKey(@"m_group_feature_id");
        }

        partial void Customizem_group_featureMapping(ModelBuilder modelBuilder);

        #endregion

        #region map_feature_group_project Mapping

        private void map_feature_group_projectMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<map_feature_group_project>().ToTable(@"map_feature_group_project");
            modelBuilder.Entity<map_feature_group_project>().Property<System.Guid>(x => x.map_feature_group_project_id).HasColumnName(@"map_feature_group_project_id").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<map_feature_group_project>().Property<int>(x => x.m_project_application_id).HasColumnName(@"m_project_application_id").ValueGeneratedNever();
            modelBuilder.Entity<map_feature_group_project>().Property<bool>(x => x.status_aktif).HasColumnName(@"status_aktif").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<map_feature_group_project>().Property<int>(x => x.m_group_feature_id).HasColumnName(@"m_group_feature_id").ValueGeneratedNever();
            modelBuilder.Entity<map_feature_group_project>().Property<int>(x => x.m_feature_id).HasColumnName(@"m_feature_id").ValueGeneratedNever();
            modelBuilder.Entity<map_feature_group_project>().Property<string>(x => x.feature_icon).HasColumnName(@"feature_icon").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<map_feature_group_project>().HasKey(@"map_feature_group_project_id");
        }

        partial void Customizemap_feature_group_projectMapping(ModelBuilder modelBuilder);

        #endregion

        private void RelationshipsMapping(ModelBuilder modelBuilder)
        {

            modelBuilder.Entity<m_organisasi>().HasMany(x => x.m_lokasi).WithOne(op => op.m_organisasi).OnDelete(DeleteBehavior.Restrict).IsRequired(true).HasForeignKey(@"m_organisasi_id");

            modelBuilder.Entity<m_lokasi>().HasOne(x => x.m_organisasi).WithMany(op => op.m_lokasi).OnDelete(DeleteBehavior.Restrict).IsRequired(true).HasForeignKey(@"m_organisasi_id");
            modelBuilder.Entity<m_lokasi>().HasMany(x => x.map_user_lokasi).WithOne(op => op.m_lokasi).OnDelete(DeleteBehavior.Restrict).IsRequired(true).HasForeignKey(@"m_lokasi_id");

            modelBuilder.Entity<m_feature>().HasMany(x => x.map_feature_group_project).WithOne(op => op.m_feature).OnDelete(DeleteBehavior.Restrict).IsRequired(true).HasForeignKey(@"m_feature_id");

            modelBuilder.Entity<map_feature_group>().HasOne(x => x.m_group_user).WithMany(op => op.map_feature_groups).OnDelete(DeleteBehavior.Restrict).IsRequired(true).HasForeignKey(@"m_group_user_id");
            modelBuilder.Entity<map_feature_group>().HasOne(x => x.map_feature_group_project).WithMany(op => op.map_feature_group).OnDelete(DeleteBehavior.Restrict).IsRequired(true).HasForeignKey(@"map_feature_group_project_id");

            modelBuilder.Entity<m_group_user>().HasMany(x => x.map_feature_groups).WithOne(op => op.m_group_user).OnDelete(DeleteBehavior.Restrict).IsRequired(true).HasForeignKey(@"m_group_user_id");
            modelBuilder.Entity<m_group_user>().HasMany(x => x.map_group_user).WithOne(op => op.m_group_user).IsRequired(true).HasForeignKey(@"m_group_user_id");

            modelBuilder.Entity<m_user>().HasMany(x => x.map_group_user).WithOne(op => op.m_user).OnDelete(DeleteBehavior.Restrict).IsRequired(true).HasForeignKey(@"m_user_id");
            modelBuilder.Entity<m_user>().HasMany(x => x.map_user_lokasi).WithOne(op => op.m_user).OnDelete(DeleteBehavior.Restrict).IsRequired(true).HasForeignKey(@"m_user_id");

            modelBuilder.Entity<map_group_user>().HasOne(x => x.m_group_user).WithMany(op => op.map_group_user).IsRequired(true).HasForeignKey(@"m_group_user_id");
            modelBuilder.Entity<map_group_user>().HasOne(x => x.m_user).WithMany(op => op.map_group_user).OnDelete(DeleteBehavior.Restrict).IsRequired(true).HasForeignKey(@"m_user_id");
            modelBuilder.Entity<map_group_user>().HasOne(x => x.m_project_application).WithMany(op => op.map_group_user).OnDelete(DeleteBehavior.Restrict).IsRequired(true).HasForeignKey(@"m_project_application_id");

            modelBuilder.Entity<m_project_application>().HasMany(x => x.map_user_lokasi).WithOne(op => op.m_project_application).OnDelete(DeleteBehavior.Restrict).IsRequired(true).HasForeignKey(@"m_project_application_id");
            modelBuilder.Entity<m_project_application>().HasMany(x => x.map_group_user).WithOne(op => op.m_project_application).OnDelete(DeleteBehavior.Restrict).IsRequired(true).HasForeignKey(@"m_project_application_id");
            modelBuilder.Entity<m_project_application>().HasMany(x => x.map_feature_group_project).WithOne(op => op.m_project_application).OnDelete(DeleteBehavior.Restrict).IsRequired(true).HasForeignKey(@"m_project_application_id");

            modelBuilder.Entity<map_user_lokasi>().HasOne(x => x.m_user).WithMany(op => op.map_user_lokasi).OnDelete(DeleteBehavior.Restrict).IsRequired(true).HasForeignKey(@"m_user_id");
            modelBuilder.Entity<map_user_lokasi>().HasOne(x => x.m_project_application).WithMany(op => op.map_user_lokasi).OnDelete(DeleteBehavior.Restrict).IsRequired(true).HasForeignKey(@"m_project_application_id");
            modelBuilder.Entity<map_user_lokasi>().HasOne(x => x.m_lokasi).WithMany(op => op.map_user_lokasi).OnDelete(DeleteBehavior.Restrict).IsRequired(true).HasForeignKey(@"m_lokasi_id");

            modelBuilder.Entity<m_group_feature>().HasMany(x => x.map_feature_group_project).WithOne(op => op.m_group_feature).OnDelete(DeleteBehavior.Restrict).IsRequired(true).HasForeignKey(@"m_group_feature_id");

            modelBuilder.Entity<map_feature_group_project>().HasOne(x => x.m_project_application).WithMany(op => op.map_feature_group_project).OnDelete(DeleteBehavior.Restrict).IsRequired(true).HasForeignKey(@"m_project_application_id");
            modelBuilder.Entity<map_feature_group_project>().HasOne(x => x.m_group_feature).WithMany(op => op.map_feature_group_project).OnDelete(DeleteBehavior.Restrict).IsRequired(true).HasForeignKey(@"m_group_feature_id");
            modelBuilder.Entity<map_feature_group_project>().HasOne(x => x.m_feature).WithMany(op => op.map_feature_group_project).OnDelete(DeleteBehavior.Restrict).IsRequired(true).HasForeignKey(@"m_feature_id");
            modelBuilder.Entity<map_feature_group_project>().HasMany(x => x.map_feature_group).WithOne(op => op.map_feature_group_project).OnDelete(DeleteBehavior.Restrict).IsRequired(true).HasForeignKey(@"map_feature_group_project_id");
        }

        partial void CustomizeMapping(ref ModelBuilder modelBuilder);

        public bool HasChanges()
        {
            return ChangeTracker.Entries().Any(e => e.State == Microsoft.EntityFrameworkCore.EntityState.Added || e.State == Microsoft.EntityFrameworkCore.EntityState.Modified || e.State == Microsoft.EntityFrameworkCore.EntityState.Deleted);
        }

        partial void OnCreated();
    }
}

namespace jasuindo_models
{
    public partial class m_organisasi {

        public m_organisasi()
        {
            this.m_lokasi = new List<m_lokasi>();
            OnCreated();
        }

        public virtual int m_organisasi_id
        {
            get;
            set;
        }

        public virtual string nama_oganisasi
        {
            get;
            set;
        }

        public virtual string alamat_organisasi
        {
            get;
            set;
        }

        public virtual bool status_aktif
        {
            get;
            set;
        }

        public virtual string email_organisasi
        {
            get;
            set;
        }

        public virtual string website_organisasi
        {
            get;
            set;
        }

        public virtual string telepon_organisasi
        {
            get;
            set;
        }

        public virtual string path_logo_organiasi
        {
            get;
            set;
        }

        public virtual string npwp_organiasi
        {
            get;
            set;
        }

        public virtual System.DateTime? create_at
        {
            get;
            set;
        }

        public virtual string create_by
        {
            get;
            set;
        }

        public virtual System.DateTime? update_at
        {
            get;
            set;
        }

        public virtual string update_by
        {
            get;
            set;
        }

        public virtual IList<m_lokasi> m_lokasi
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }
    public partial class m_lokasi {

        public m_lokasi()
        {
            this.map_user_lokasi = new List<map_user_lokasi>();
            OnCreated();
        }

        public virtual int m_lokasi_id
        {
            get;
            set;
        }

        public virtual int m_organisasi_id
        {
            get;
            set;
        }

        public virtual int parent_lokasi_id
        {
            get;
            set;
        }

        public virtual int parent_index
        {
            get;
            set;
        }

        public virtual string nama_lokasi
        {
            get;
            set;
        }

        public virtual string kode_lokasi
        {
            get;
            set;
        }

        public virtual string provinsi
        {
            get;
            set;
        }

        public virtual string kabupaten
        {
            get;
            set;
        }

        public virtual string kecamatan
        {
            get;
            set;
        }

        public virtual string kelurahan
        {
            get;
            set;
        }

        public virtual string alamat
        {
            get;
            set;
        }

        public virtual bool status_aktif
        {
            get;
            set;
        }

        public virtual System.DateTime? create_at
        {
            get;
            set;
        }

        public virtual string create_by
        {
            get;
            set;
        }

        public virtual System.DateTime? update_at
        {
            get;
            set;
        }

        public virtual string update_by
        {
            get;
            set;
        }

        public virtual string name_location_secondary
        {
            get;
            set;
        }

        public virtual m_organisasi m_organisasi
        {
            get;
            set;
        }

        public virtual IList<map_user_lokasi> map_user_lokasi
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }
    public partial class m_kelurahan_desa {

        public m_kelurahan_desa()
        {
            OnCreated();
        }

        public virtual string m_kelurahan_desa_id
        {
            get;
            set;
        }

        public virtual string nama_kelurahan_desa
        {
            get;
            set;
        }

        public virtual string nama_kecamatan
        {
            get;
            set;
        }

        public virtual string nama_kabupaten_kota
        {
            get;
            set;
        }

        public virtual string jenis_kabupaten_kota
        {
            get;
            set;
        }

        public virtual string nama_propinsi
        {
            get;
            set;
        }

        public virtual string kode_pos
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }
    public partial class m_feature {

        public m_feature()
        {
            this.map_feature_group_project = new List<map_feature_group_project>();
            OnCreated();
        }

        public virtual int m_feature_id
        {
            get;
            set;
        }

        public virtual string m_feature_name
        {
            get;
            set;
        }

        public virtual int? index
        {
            get;
            set;
        }

        public virtual string name_link_feature
        {
            get;
            set;
        }

        public virtual bool status
        {
            get;
            set;
        }

        public virtual System.DateTime? create_at
        {
            get;
            set;
        }

        public virtual string create_by
        {
            get;
            set;
        }

        public virtual System.DateTime? update_at
        {
            get;
            set;
        }

        public virtual string update_by
        {
            get;
            set;
        }

        public virtual string feature_icon
        {
            get;
            set;
        }

        public virtual IList<map_feature_group_project> map_feature_group_project
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }
    public partial class map_feature_group {

        public map_feature_group()
        {
            OnCreated();
        }

        public virtual System.Guid map_feature_group_id
        {
            get;
            set;
        }

        public virtual int m_group_user_id
        {
            get;
            set;
        }

        public virtual string action_feature
        {
            get;
            set;
        }

        public virtual System.DateTime? create_at
        {
            get;
            set;
        }

        public virtual string create_by
        {
            get;
            set;
        }

        public virtual System.DateTime? update_at
        {
            get;
            set;
        }

        public virtual string update_by
        {
            get;
            set;
        }

        public virtual System.Guid map_feature_group_project_id
        {
            get;
            set;
        }

        public virtual m_group_user m_group_user
        {
            get;
            set;
        }

        public virtual map_feature_group_project map_feature_group_project
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }
    public partial class m_group_user {

        public m_group_user()
        {
            this.map_feature_groups = new List<map_feature_group>();
            this.map_group_user = new List<map_group_user>();
            OnCreated();
        }

        public virtual int m_group_user_id
        {
            get;
            set;
        }

        public virtual string m_group_user_name
        {
            get;
            set;
        }

        public virtual bool status
        {
            get;
            set;
        }

        public virtual System.DateTime? create_at
        {
            get;
            set;
        }

        public virtual string create_by
        {
            get;
            set;
        }

        public virtual System.DateTime? update_at
        {
            get;
            set;
        }

        public virtual string update_by
        {
            get;
            set;
        }

        public virtual IList<map_feature_group> map_feature_groups
        {
            get;
            set;
        }

        public virtual IList<map_group_user> map_group_user
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }
    public partial class m_user {

        public m_user()
        {
            this.map_group_user = new List<map_group_user>();
            this.map_user_lokasi = new List<map_user_lokasi>();
            OnCreated();
        }

        public virtual System.Guid m_user_id
        {
            get;
            set;
        }

        public virtual string m_username
        {
            get;
            set;
        }

        public virtual string m_user_password
        {
            get;
            set;
        }

        public virtual string m_user_email
        {
            get;
            set;
        }

        public virtual bool status
        {
            get;
            set;
        }

        public virtual string status_aktif
        {
            get;
            set;
        }

        public virtual System.DateTime? create_at
        {
            get;
            set;
        }

        public virtual string create_by
        {
            get;
            set;
        }

        public virtual System.DateTime? update_at
        {
            get;
            set;
        }

        public virtual string update_by
        {
            get;
            set;
        }

        public virtual string ref1
        {
            get;
            set;
        }

        public virtual string ref2
        {
            get;
            set;
        }

        public virtual string ref3
        {
            get;
            set;
        }

        public virtual IList<map_group_user> map_group_user
        {
            get;
            set;
        }

        public virtual IList<map_user_lokasi> map_user_lokasi
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }
    public partial class map_group_user {

        public map_group_user()
        {
            OnCreated();
        }

        public virtual System.Guid map_group_user_id
        {
            get;
            set;
        }

        public virtual bool status_aktif
        {
            get;
            set;
        }

        public virtual int m_group_user_id
        {
            get;
            set;
        }

        public virtual int m_project_application_id
        {
            get;
            set;
        }

        public virtual System.Guid m_user_id
        {
            get;
            set;
        }

        public virtual System.DateTime? create_at
        {
            get;
            set;
        }

        public virtual string create_by
        {
            get;
            set;
        }

        public virtual System.DateTime? update_at
        {
            get;
            set;
        }

        public virtual string update_by
        {
            get;
            set;
        }

        public virtual m_group_user m_group_user
        {
            get;
            set;
        }

        public virtual m_user m_user
        {
            get;
            set;
        }

        public virtual m_project_application m_project_application
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }
    public partial class m_action_feature {

        public m_action_feature()
        {
            OnCreated();
        }

        public virtual int m_action_feature_id
        {
            get;
            set;
        }

        public virtual string m_action_feature_name
        {
            get;
            set;
        }

        public virtual System.DateTime? create_at
        {
            get;
            set;
        }

        public virtual string create_by
        {
            get;
            set;
        }

        public virtual System.DateTime? update_at
        {
            get;
            set;
        }

        public virtual string update_by
        {
            get;
            set;
        }

        public virtual bool status
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }
    public partial class m_project_application {

        public m_project_application()
        {
            this.map_user_lokasi = new List<map_user_lokasi>();
            this.map_group_user = new List<map_group_user>();
            this.map_feature_group_project = new List<map_feature_group_project>();
            OnCreated();
        }

        public virtual int m_project_application_id
        {
            get;
            set;
        }

        public virtual string m_project_application_name
        {
            get;
            set;
        }

        public virtual bool status_aktif
        {
            get;
            set;
        }

        public virtual string key_project
        {
            get;
            set;
        }

        public virtual System.DateTime? create_at
        {
            get;
            set;
        }

        public virtual string create_by
        {
            get;
            set;
        }

        public virtual System.DateTime? update_at
        {
            get;
            set;
        }

        public virtual string update_by
        {
            get;
            set;
        }

        public virtual string type_project
        {
            get;
            set;
        }

        public virtual string scope_fitur_project
        {
            get;
            set;
        }

        public virtual IList<map_user_lokasi> map_user_lokasi
        {
            get;
            set;
        }

        public virtual IList<map_group_user> map_group_user
        {
            get;
            set;
        }

        public virtual IList<map_feature_group_project> map_feature_group_project
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }
    public partial class map_user_lokasi {

        public map_user_lokasi()
        {
            OnCreated();
        }

        public virtual System.Guid map_user_lokasi_id
        {
            get;
            set;
        }

        public virtual System.DateTime? create_at
        {
            get;
            set;
        }

        public virtual string create_by
        {
            get;
            set;
        }

        public virtual System.DateTime? update_at
        {
            get;
            set;
        }

        public virtual string update_by
        {
            get;
            set;
        }

        public virtual System.Guid m_user_id
        {
            get;
            set;
        }

        public virtual int m_project_application_id
        {
            get;
            set;
        }

        public virtual int m_lokasi_id
        {
            get;
            set;
        }

        public virtual m_user m_user
        {
            get;
            set;
        }

        public virtual m_project_application m_project_application
        {
            get;
            set;
        }

        public virtual m_lokasi m_lokasi
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }
    public partial class m_group_feature {

        public m_group_feature()
        {
            this.map_feature_group_project = new List<map_feature_group_project>();
            OnCreated();
        }

        public virtual int m_group_feature_id
        {
            get;
            set;
        }

        public virtual bool status
        {
            get;
            set;
        }

        public virtual int index
        {
            get;
            set;
        }

        public virtual System.DateTime? create_at
        {
            get;
            set;
        }

        public virtual string create_by
        {
            get;
            set;
        }

        public virtual System.DateTime? update_at
        {
            get;
            set;
        }

        public virtual string update_by
        {
            get;
            set;
        }

        public virtual string group_feature_name
        {
            get;
            set;
        }

        public virtual IList<map_feature_group_project> map_feature_group_project
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }
    public partial class map_feature_group_project {

        public map_feature_group_project()
        {
            this.map_feature_group = new List<map_feature_group>();
            OnCreated();
        }

        public virtual System.Guid map_feature_group_project_id
        {
            get;
            set;
        }

        public virtual int m_project_application_id
        {
            get;
            set;
        }

        public virtual bool status_aktif
        {
            get;
            set;
        }

        public virtual int m_group_feature_id
        {
            get;
            set;
        }

        public virtual int m_feature_id
        {
            get;
            set;
        }

        public virtual string feature_icon
        {
            get;
            set;
        }

        public virtual m_project_application m_project_application
        {
            get;
            set;
        }

        public virtual m_group_feature m_group_feature
        {
            get;
            set;
        }

        public virtual m_feature m_feature
        {
            get;
            set;
        }

        public virtual IList<map_feature_group> map_feature_group
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
